[project]
name = "email-sender-h"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask==3.0.0",
    "flask-cors==4.0.0",
]
